name: UnitTests

on: [push]

jobs:
  test-engine:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: test js-engine
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
        working-directory: js-engine
      - run: npm run test
        working-directory: js-engine
  test-parer:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: test parser
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python -m unittest
        working-directory: parser
